POST http://localhost:12345/api/parties
Content-Type: application/json

{
      "title": "uma festa",
      "authot": "Patricio",
      "description": "uma festa legal",
      "budget": 2000
}

###
GET http://localhost:12345/api/parties

